"""Add route name

Revision ID: 0aeaa87e0693
Revises: d66c3e17fad6
Create Date: 2026-07-27 22:24:35.669854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0aeaa87e0693'
down_revision: Union[str, Sequence[str], None] = 'd66c3e17fad6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attempts', sa.Column('num_attempts', sa.Integer(), nullable=False))
    op.drop_column('attempts', 'attempt_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attempts', sa.Column('attempt_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('attempts', 'num_attempts')
    # ### end Alembic commands ###
