"""Add route status

Revision ID: d66c3e17fad6
Revises: 2bee76514134
Create Date: 2026-07-26 21:44:58.830297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'd66c3e17fad6'
down_revision: Union[str, Sequence[str], None] = '2bee76514134'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

route_status_enum = postgresql.ENUM(
    "active",
    "retired",
    name="route_status_enum",
    create_type=False,
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
        # 1. Create enum type
    route_status_enum.create(
        op.get_bind(),
        checkfirst=True,
    )
    
    op.drop_constraint(op.f('route_style_association_route_id_fkey'), 'route_style_association', type_='foreignkey')
    op.create_foreign_key(None, 'route_style_association', 'routes', ['route_id'], ['id'], ondelete='CASCADE')
    op.add_column('routes', sa.Column('set_date', sa.Date(), nullable=True))
    op.add_column('routes', sa.Column('retired_date', sa.Date(), nullable=True))
    op.add_column('routes', sa.Column('status', sa.Enum('active', 'retired', name='route_status_enum'), server_default='active', nullable=False))
    op.alter_column('routes', 'colour',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('routes', 'wall',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.create_index(op.f('ix_routes_id'), 'routes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_routes_id'), table_name='routes')
    op.alter_column('routes', 'wall',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('routes', 'colour',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_column('routes', 'status')
    op.drop_column('routes', 'retired_date')
    op.drop_column('routes', 'set_date')
    op.drop_constraint(None, 'route_style_association', type_='foreignkey')
    op.create_foreign_key(op.f('route_style_association_route_id_fkey'), 'route_style_association', 'routes', ['route_id'], ['id'])
    
    route_status_enum.drop(
        op.get_bind(),
        checkfirst=True,
    )
    # ### end Alembic commands ###
